"""Inicial

Revision ID: 978feeaa7037
Revises: 
Create Date: 2021-10-13 01:19:41.429518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978feeaa7037'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_id'), ['id'], unique=False)

    op.create_table('pratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('disponivel', sa.Boolean(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pratos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pratos_id'), ['id'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('tipo_acesso', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_id'), ['id'], unique=False)

    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('prato_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prato_id'], ['pratos.id'], name='fk_pratos'),
    sa.ForeignKeyConstraint(['user_id'], ['clientes.id'], name='fk_clientes'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidos_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_id'))

    op.drop_table('pedidos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_id'))

    op.drop_table('usuarios')
    with op.batch_alter_table('pratos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pratos_id'))

    op.drop_table('pratos')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_id'))

    op.drop_table('clientes')
    # ### end Alembic commands ###
