"""Adicionando colunas de datas de criacao e atualizacao

Revision ID: bee8ca4c5aae
Revises: 978feeaa7037
Create Date: 2021-10-15 01:01:42.014855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bee8ca4c5aae'
down_revision = '978feeaa7037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_criacao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data_atualizacao', sa.DateTime(), nullable=True))

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('data_criacao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data_atualizacao', sa.DateTime(), nullable=True))

    with op.batch_alter_table('pratos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_criacao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data_atualizacao', sa.DateTime(), nullable=True))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_criacao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data_atualizacao', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('data_atualizacao')
        batch_op.drop_column('data_criacao')

    with op.batch_alter_table('pratos', schema=None) as batch_op:
        batch_op.drop_column('data_atualizacao')
        batch_op.drop_column('data_criacao')

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('data_atualizacao')
        batch_op.drop_column('data_criacao')
        batch_op.drop_column('status')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('data_atualizacao')
        batch_op.drop_column('data_criacao')

    # ### end Alembic commands ###
