"""Alterando nome da coluna user_id para cliente_id da tabela Pedidos

Revision ID: ceeedd981d9f
Revises: bee8ca4c5aae
Create Date: 2021-10-15 01:16:23.343156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceeedd981d9f'
down_revision = 'bee8ca4c5aae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_clientes', type_='foreignkey')
        batch_op.create_foreign_key('fk_clientes', 'clientes', ['cliente_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_clientes', type_='foreignkey')
        batch_op.create_foreign_key('fk_clientes', 'clientes', ['user_id'], ['id'])
        batch_op.drop_column('cliente_id')

    # ### end Alembic commands ###
